# Generated by Django 2.0.4 on 2018-05-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='text',
            new_name='code',
        ),
        migrations.AddField(
            model_name='item',
            name='description_r',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='name_r',
            field=models.CharField(default='', max_length=20),
        ),
    ]
