# Generated by Django 2.0.4 on 2018-08-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20180504_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termin', models.CharField(default='', max_length=20)),
                ('definition', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
