# Generated by Django 2.0.4 on 2018-08-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_theory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theory',
            new_name='Graph',
        ),
    ]
